/*
 * This file is generated by jOOQ.
 */
package com.bigdata.boot.chapter32.jooq;


import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<Record> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<Record> CONSTRAINT_F = UniqueKeys0.CONSTRAINT_F;
    public static final UniqueKey<Record> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<Record> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> FK_BOOK_AUTHOR = ForeignKeys0.FK_BOOK_AUTHOR;
    public static final ForeignKey<Record, Record> FK_BOOK_LANGUAGE = ForeignKeys0.FK_BOOK_LANGUAGE;
    public static final ForeignKey<Record, Record> FK_B2BS_BOOK_STORE = ForeignKeys0.FK_B2BS_BOOK_STORE;
    public static final ForeignKey<Record, Record> FK_B2BS_BOOK = ForeignKeys0.FK_B2BS_BOOK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> CONSTRAINT_7 = Internal.createUniqueKey(Author.AUTHOR, "CONSTRAINT_7", new TableField[] { Author.AUTHOR.ID }, true);
        public static final UniqueKey<Record> CONSTRAINT_1 = Internal.createUniqueKey(Book.BOOK, "CONSTRAINT_1", new TableField[] { Book.BOOK.ID }, true);
        public static final UniqueKey<Record> CONSTRAINT_F = Internal.createUniqueKey(BookStore.BOOK_STORE, "CONSTRAINT_F", new TableField[] { BookStore.BOOK_STORE.NAME }, true);
        public static final UniqueKey<Record> CONSTRAINT_2 = Internal.createUniqueKey(BookToBookStore.BOOK_TO_BOOK_STORE, "CONSTRAINT_2", new TableField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME, BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
        public static final UniqueKey<Record> CONSTRAINT_C = Internal.createUniqueKey(Language.LANGUAGE, "CONSTRAINT_C", new TableField[] { Language.LANGUAGE.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<Record, Record> FK_BOOK_AUTHOR = Internal.createForeignKey(Keys.CONSTRAINT_7, Book.BOOK, "FK_BOOK_AUTHOR", new TableField[] { Book.BOOK.AUTHOR_ID }, true);
        public static final ForeignKey<Record, Record> FK_BOOK_LANGUAGE = Internal.createForeignKey(Keys.CONSTRAINT_C, Book.BOOK, "FK_BOOK_LANGUAGE", new TableField[] { Book.BOOK.LANGUAGE_ID }, true);
        public static final ForeignKey<Record, Record> FK_B2BS_BOOK_STORE = Internal.createForeignKey(Keys.CONSTRAINT_F, BookToBookStore.BOOK_TO_BOOK_STORE, "FK_B2BS_BOOK_STORE", new TableField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME }, true);
        public static final ForeignKey<Record, Record> FK_B2BS_BOOK = Internal.createForeignKey(Keys.CONSTRAINT_1, BookToBookStore.BOOK_TO_BOOK_STORE, "FK_B2BS_BOOK", new TableField[] { BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
    }
}
